######################## default configuration ####################
baseURL = "https://hungryhairwax.co.za/"
languageCode = "en"
title = "hungryhairwax"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Products"
  URL = "products"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 3

  ############# footer menu #############
  [[menu.footer]]
  name = "Products"
  URL = "products"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "FAQ"
  URL = "faq"
  weight = 3

  [[menu.footer]]
  name = "Refund Policy"
  URL = "refund-policy"
  weight = 4

#################### default parameters ################################

[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "hungryhairwax home"
author = "George Anthony Heginbotham"
# Contact Information
email = "hungryhairwax@gmail.com"
location = "Cape Town, South Africa"
# copyright
copyright = "Copyright &copy; | 2021 George Anthony Heginbotham | All Rights Reserved"
# Snipcart Credentials
snipcartApiKey = "EDFYj0bqEMTCS5ZPlMRiUakXPfYORIpgCupF709b-kZBuuCUF9pNJip0XhFroWDvF6pcynu1qau6QzsG"
currencySymbol = "R"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "#"

  [[params.social]]
  icon = "ti-twitter-alt"
  link = "#"

  [[params.social]]
  icon = "ti-youtube"
  link = "#"

  [[params.social]]
  icon = "ti-instagram"
  link = "#"

  [[params.social]]
  icon = "ti-pinterest"
  link = "#"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
