######################## default configuration ####################
baseURL = "https://hungryhairwax.co.za/"
languageCode = "en"
title = "hungryhairwax"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Product"
  URL = "haircareproducts/natural-hair-wax"
  weight = 1
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 3

  ############# footer menu #############
  [[menu.footer]]
  name = "Product"
  URL = "haircareproducts/natural-hair-wax"
  weight = 1
  

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "FAQ"
  URL = "faq"
  weight = 3

  [[menu.footer]]
  name = "Refund Policy"
  URL = "refund-policy"
  weight = 4

#################### default parameters ################################

[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "hungryhairwax natural hair wax for men"
author = "George Anthony Heginbotham"
# Contact Information
email = "hungryhairwax@gmail.com"
location = "Cape Town, South Africa"
# copyright
copyright = "Copyright &copy; | 2021 George Anthony Heginbotham | All Rights Reserved"
# Snipcart Credentials
snipcartApiKey = "ZDYxMTEwYmMtOWFmMi00Mjk2LTljZTEtZDFhYjBjZmU2NWI3NjM3MzMzMzgyMjcwNzE0MjA0"
currencySymbol = "R"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "https://www.facebook.com/hungryhairwax"

  [[params.social]]
  icon = "ti-twitter-alt"
  link = "https://twitter.com/hungryhairwax"

  [[params.social]]
  icon = "ti-youtube"
  link = "https://www.youtube.com/channel/UC10LGDWeIz84EkhsUajIprg"

  [[params.social]]
  icon = "ti-instagram"
  link = "https://www.instagram.com/hungryhairwax/"

  [[params.social]]
  icon = "ti-pinterest"
  link = "https://za.pinterest.com/hungryhairwax/_saved/"

  # Contact Form
  [params.contact]
  formAction = "https://formspree.io/f/xyylzpbk" # contact form works with formspree.io
